// This file is auto-generated by iconify_lustre.

import gleam/list
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import lustre/element/svg

pub fn github(attributes: List(Attribute(msg))) -> Element(msg) {
  svg.svg(
    add_defaults(attributes, [
      attribute.class("icon"),
      attribute.attribute("viewBox", "0 0 24 24"),
      attribute.attribute("xmlns", "http://www.w3.org/2000/svg"),
    ]),
    [
      svg.g(
        [
          attribute.attribute("stroke-width", "2"),
          attribute.attribute("stroke-linejoin", "round"),
          attribute.attribute("stroke-linecap", "round"),
          attribute.attribute("stroke", "currentColor"),
          attribute.attribute("fill", "none"),
        ],
        [
          svg.path([
            attribute.attribute(
              "d",
              "M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5c.08-1.25-.27-2.48-1-3.5c.28-1.15.28-2.35 0-3.5c0 0-1 0-3 1.5c-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5c-.39.49-.68 1.05-.85 1.65S8.93 17.38 9 18v4",
            ),
          ]),
          svg.path([attribute.attribute("d", "M9 18c-4.51 2-5-2-7-2")]),
        ],
      ),
    ],
  )
}

pub fn sun(attributes: List(Attribute(msg))) -> Element(msg) {
  svg.svg(
    add_defaults(attributes, [
      attribute.class("icon"),
      attribute.attribute("viewBox", "0 0 24 24"),
      attribute.attribute("xmlns", "http://www.w3.org/2000/svg"),
    ]),
    [
      svg.g(
        [
          attribute.attribute("stroke-width", "2"),
          attribute.attribute("stroke-linejoin", "round"),
          attribute.attribute("stroke-linecap", "round"),
          attribute.attribute("stroke", "currentColor"),
          attribute.attribute("fill", "none"),
        ],
        [
          svg.circle([
            attribute.attribute("r", "4"),
            attribute.attribute("cy", "12"),
            attribute.attribute("cx", "12"),
          ]),
          svg.path([
            attribute.attribute(
              "d",
              "M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32l1.41 1.41M2 12h2m16 0h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41",
            ),
          ]),
        ],
      ),
    ],
  )
}

pub fn moon(attributes: List(Attribute(msg))) -> Element(msg) {
  svg.svg(
    add_defaults(attributes, [
      attribute.class("icon"),
      attribute.attribute("viewBox", "0 0 24 24"),
      attribute.attribute("xmlns", "http://www.w3.org/2000/svg"),
    ]),
    [
      svg.path([
        attribute.attribute(
          "d",
          "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401",
        ),
        attribute.attribute("stroke-width", "2"),
        attribute.attribute("stroke-linejoin", "round"),
        attribute.attribute("stroke-linecap", "round"),
        attribute.attribute("stroke", "currentColor"),
        attribute.attribute("fill", "none"),
      ]),
    ],
  )
}

pub fn hamburger(attributes: List(Attribute(msg))) -> Element(msg) {
  svg.svg(
    add_defaults(attributes, [
      attribute.class("icon"),
      attribute.attribute("viewBox", "0 0 24 24"),
      attribute.attribute("xmlns", "http://www.w3.org/2000/svg"),
    ]),
    [
      svg.g(
        [
          attribute.attribute("stroke-width", "2"),
          attribute.attribute("stroke-linejoin", "round"),
          attribute.attribute("stroke-linecap", "round"),
          attribute.attribute("stroke", "currentColor"),
          attribute.attribute("fill", "none"),
        ],
        [
          svg.path([
            attribute.attribute(
              "d",
              "M12 16H4a2 2 0 1 1 0-4h16a2 2 0 1 1 0 4h-4.25M5 12a2 2 0 0 1-2-2a9 7 0 0 1 18 0a2 2 0 0 1-2 2M5 16a2 2 0 0 0-2 2a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3a2 2 0 0 0-2-2q0 0 0 0",
            ),
          ]),
          svg.path([
            attribute.attribute(
              "d",
              "m6.67 12l6.13 4.6a2 2 0 0 0 2.8-.4l3.15-4.2",
            ),
          ]),
        ],
      ),
    ],
  )
}

pub fn tangled(attributes: List(Attribute(msg))) -> Element(msg) {
  svg.svg(
    add_defaults(attributes, [
      attribute.class("icon"),
      attribute.attribute("viewBox", "0 0 24 24"),
      attribute.attribute("xmlns", "http://www.w3.org/2000/svg"),
    ]),
    [
      svg.path([
        attribute.attribute(
          "d",
          "M15.823 23.573c-.78-.006-1.376-.233-2.022-.629c-.926-.489-1.633-1.31-2.139-2.215c-.803 1-1.876 1.606-3.078 1.949c-.512.149-1.408.3-2.893-.24c-2.141-.721-3.7-2.956-3.524-5.232c-.032-.944.31-1.87.797-2.667c-1.297-.698-2.355-1.87-2.76-3.308c-.246-.787-.236-1.635-.145-2.444c.325-1.91 1.754-3.571 3.593-4.168c.734-1.678 2.336-2.93 4.15-3.184a5.5 5.5 0 0 1 3.507.699C12.845.425 15.521-.08 17.565.97c1.558.746 2.673 2.304 2.944 4.002c1.483.596 2.732 1.812 3.222 3.354c.328.956.339 2.008.126 2.989c-.379 1.53-1.456 2.833-2.85 3.545c.003.272.896 2.236.746 3.718c-.032 1.853-1.204 3.609-2.829 4.462c-.948.555-2.071.544-3.101.533M11.38 18.24c1.314-.147 2.176-1.296 2.845-2.331c.316-.472.558-1 .798-1.501c.311.286.575.825 1.068.954c.518.162 1.126.03 1.444-.442c.608-1.137.308-2.51-.046-3.687c-.218-.677-.504-1.371-1.048-1.85c.116-.822-.369-1.655-1.058-2.085c-.588.47-1.482.467-2.048-.036c-1.087 1.112-2.082 1.075-3.044.194c-.216-.198-.629 1.208-2.076.412c-.831.698-1.476 1.37-2.047 2.339c-.555 1.043-1.137 1.97-1.187 3.103c-.024.662.492 1.356 1.191 1.302c.699.063 1.174-.627 1.703-.914c.08.925.168 1.918.48 2.82c.357 1.168 1.616 1.91 2.808 1.74zm.682-3.486c-.64-.393-.332-1.246-.357-1.866c.063-.747.115-1.533.45-2.214c.354-.485 1.219-.298 1.257.325c-.025.626-.312 1.25-.278 1.9c-.074.542.054 1.151-.185 1.647c-.197.274-.596.354-.887.208m-2.792-.357c-.602-.328-.41-1.153-.505-1.726c.079-.663.013-1.505.567-1.97c.542-.38 1.28.27 1.023.865c-.273.753-.094 1.576-.088 2.339a.708.708 0 0 1-.997.492",
        ),
        attribute.attribute("fill", "currentColor"),
      ]),
    ],
  )
}

fn add_defaults(
  attributes: List(Attribute(msg)),
  defaults: List(Attribute(msg)),
) -> List(Attribute(msg)) {
  list.fold(defaults, attributes, fn(accumulator, default) {
    case list.any(accumulator, fn(item) { item.name == default.name }) {
      False -> [default, ..accumulator]
      True -> accumulator
    }
  })
}
